#!/usr/bin/env sh
  if [ "$DOCKER_TAG" = "latest" ]; then
    docker build -f Dockerfile -t ${IMAGE_NAME} .
  else
    docker build -f Dockerfile.tag --build-arg VERSION_ARG="v$DOCKER_TAG" -t ${IMAGE_NAME} .
  fi
